name: Robot Framework CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Use the latest version

      - name: Set up Python
        uses: actions/setup-python@v4  # Use the latest version
        with:
          python-version: '3.8'  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create results directory
        run: |
          mkdir -p results/${{ github.run_id }}  # Create a unique directory for this run

      - name: Run Robot Framework tests
        run: |
          robot --outputdir results/${{ github.run_id }} tests/  # Store results in the unique directory

      - name: Upload Test Results
        uses: actions/upload-artifact@v4  # Use the latest version
        with:
          name: robot-results-${{ github.run_id }}  # Name the artifact with the run ID
          path: results/${{ github.run_id }}/  # Path to the unique results directory
