name: Robot Framework CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  robot-framework:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Use the latest version

      - name: Set up Python
        uses: actions/setup-python@v4  # Use the latest version
        with:
          python-version: '3.8'  # Specify the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

#      - name: Install Google Chrome
#        run: |
#          sudo apt update
#          sudo apt install -y google-chrome-stable

      - name: Create results directory
        run: |
          mkdir -p results/${{ github.run_id }}  # Create a unique directory for this run

      - name: Run Robot Framework tests in Chrome
        # continue-on-error: true  # Ensures the job doesn't fail if tests fail
        run: |
          robot --outputdir results/${{ github.run_id }}/chrome --variable DEFAULT_HEADLESS:True --exclude Java tests/  # Store results in the unique directory

      - name: Run Robot Framework tests in Firefox
        run: |
          robot -d results/${{ github.run_id }}/firefox -v DEFAULT_HEADLESS:True -v DEFAULT_BROWSER:firefox -e java tests/

      - name: Upload Test Results
        uses: actions/upload-artifact@v4  # Use the latest version
        if: always()  # Ensures this step runs even if previous steps failed
        with:
          name: robot-results-${{ github.run_id }}  # Name the artifact with the run ID
          path: results/${{ github.run_id }}/  # Path to the unique results directory

  notification:
    runs-on: ubuntu-latest
    needs: robot-framework  # Ensures this job waits for robot-framework to complete
    if: failure()  # Triggers only if the previous job failed
    steps:
      - name: Send Email via Resend SMTP
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: 587  # Resend supports ports 25, 2525, 587
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "🚨 GitHub Actions Workflow Failed!"
          body: "The workflow has failed. Check logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          to: ${{ secrets.EMAIL_RECIPIENTS }}
          from: ${{ secrets.SMTP_SEND_AS }}
